name: Final project workflow
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
defaults:
    run:
        shell: bash
jobs:
    lint-code:
        name: 'Linting code'
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout reposiroty'
              uses: actions/checkout@v4
            - name: 'Install dependencies'
              run: |
                python -m pip install --upgrade pip
                pip install pylint flask flask_login flask_sqlalchemy
            - name: 'Test python code with pylint'
              working-directory: ./site
              run: |
                pylint /app
    build-publish-image:
        name: 'Build and publish final project image'
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout reposiroty'
            uses: actions/checkout@v4
          
          - name: 'Build image'
            run: |
              docker build -t mantelis900726/final-project-image:latest .
          - name: 'Publish image'
            run: |
              docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
              docker push mantelis900726/final-project-image:latest